/*
 * Generated by XDoclet - Do not edit!
 */
package com.paic.pafa2.biz.interfaces;

/**
 * Remote interface for PolicyEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface PolicyEJB
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public boolean insert( com.paic.pafa2.common.PafaDTO dto )
      throws com.paic.pafa2.common.PafaBusinessException, java.rmi.RemoteException;

   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public com.paic.pafa2.common.PafaDTO query( com.paic.pafa2.common.PafaDTO dto,java.lang.String queryKey )
      throws com.paic.pafa2.common.PafaBusinessException, java.rmi.RemoteException;

   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public boolean update( com.paic.pafa2.common.PafaDTO dto,java.lang.String updateKey )
      throws com.paic.pafa2.common.PafaBusinessException, java.rmi.RemoteException;

   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public int delete( com.paic.pafa2.common.PafaDTO dto,java.lang.String deleteKey )
      throws com.paic.pafa2.common.PafaBusinessException, java.rmi.RemoteException;

}
