/*
 * Generated by XDoclet - Do not edit!
 */
package com.paic.pafa2.biz.interfaces;

/**
 * Home interface for PolicyEJB.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface PolicyEJBHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PolicyEJB";
   public static final String JNDI_NAME="ejb/PolicyEJB";

   public com.paic.pafa2.biz.interfaces.PolicyEJB create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
